CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1,2,3)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 16
PRINT_FREQ: 20

DATASET:
  DATASET: bdd
  ROOT: "/root/autodl-tmp/DSNet/data/"
  TEST_SET: 'list/bdd/val.lst'
  TRAIN_SET: 'list/bdd/train.lst'
  NUM_CLASSES: 19
MODEL:
  NAME: 'dsnet_head64'
  NUM_OUTPUTS: 2
  PRETRAINED: ""
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1280
  - 720
  BASE_SIZE: 1280
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 300
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 13
TEST:
  IMAGE_SIZE:
  - 1280
  - 720
  BASE_SIZE: 1280
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
