CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1,2,3)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 50

DATASET:
  DATASET: ade20k
  ROOT: "/root/autodl-tmp/DSNet/data/"
  TEST_SET: 'list/ade20k/val.lst'
  TRAIN_SET: 'list/ade20k/train.lst'
  NUM_CLASSES: 150
MODEL:
  NAME: 'dsnet_m'
  NUM_OUTPUTS: 3
  PRETRAINED: ""
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 253
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0001
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 13
TEST:
  IMAGE_SIZE:
  - 512
  - 512
  BASE_SIZE: 512
  BATCH_SIZE_PER_GPU: 4
  FLIP_TEST: false
  MULTI_SCALE: false 
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
